apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer  # <-- This is the key change
  selector:
    app: my-app  # Make sure this matches the labels in your deployment
  ports:
    - protocol: TCP
      port: 80            # Exposed port
      targetPort: 3000    # The port your container is listening on (change if needed)
